version: 0.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: xDa4WI1OqgjorxnUdEoQs/RhMSgjl3hn8iWvNVFFwzXAXM/CsWSOg1yES72MimYp
before_build:
  - git clone https://github.com/SwagAttack/SwagAttack_Gameserver_Mirror ../SwagAttack_Gameserver_Mirror
  - dotnet build ../SwagAttack_Gameserver_Mirror/GameServer/Domain/Domain.csproj
  - nuget restore GUI/GUI.sln
build_script:
  - dotnet build GUI/GUI.sln
after_test:
  - cmd: after_test.cmd